// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.26.0
// source: pkg/pb/assets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应结构
type UniversalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应码
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 响应描述
}

func (x *UniversalResp) Reset() {
	*x = UniversalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalResp) ProtoMessage() {}

func (x *UniversalResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalResp.ProtoReflect.Descriptor instead.
func (*UniversalResp) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{0}
}

func (x *UniversalResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UniversalResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MintCoinsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                     // 区块链账户
	OrgMspId string `protobuf:"bytes,2,opt,name=org_msp_id,json=orgMspId,proto3" json:"org_msp_id,omitempty"` // 账户所属组织
	Amount   uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                      // 增发数量
}

func (x *MintCoinsReq) Reset() {
	*x = MintCoinsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MintCoinsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCoinsReq) ProtoMessage() {}

func (x *MintCoinsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCoinsReq.ProtoReflect.Descriptor instead.
func (*MintCoinsReq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{1}
}

func (x *MintCoinsReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MintCoinsReq) GetOrgMspId() string {
	if x != nil {
		return x.OrgMspId
	}
	return ""
}

func (x *MintCoinsReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MintCoinsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`     // 状态码
	Desc   string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`      // 描述信息
	Amount uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // 增发数量
}

func (x *MintCoinsResp) Reset() {
	*x = MintCoinsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MintCoinsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCoinsResp) ProtoMessage() {}

func (x *MintCoinsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCoinsResp.ProtoReflect.Descriptor instead.
func (*MintCoinsResp) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{2}
}

func (x *MintCoinsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MintCoinsResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *MintCoinsResp) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // 区块链账户
	Org     string `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`         // 账户所属组织
}

func (x *UserData) Reset() {
	*x = UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{3}
}

func (x *UserData) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserData) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 响应码
	Msg  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 响应描述
	Data *UserData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RegisterResp) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CoinsExchangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                      // 账户
	OrgMspId  string `protobuf:"bytes,2,opt,name=org_msp_id,json=orgMspId,proto3" json:"org_msp_id,omitempty"`  // 账户所属组织
	Amount    uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                       // 数量(单位:分)
	Genre     int64  `protobuf:"varint,4,opt,name=genre,proto3" json:"genre,omitempty"`                         // 类型(1-充值 2-提现)
	PaymentId string `protobuf:"bytes,5,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // 支付id
}

func (x *CoinsExchangeReq) Reset() {
	*x = CoinsExchangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinsExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinsExchangeReq) ProtoMessage() {}

func (x *CoinsExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinsExchangeReq.ProtoReflect.Descriptor instead.
func (*CoinsExchangeReq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{5}
}

func (x *CoinsExchangeReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CoinsExchangeReq) GetOrgMspId() string {
	if x != nil {
		return x.OrgMspId
	}
	return ""
}

func (x *CoinsExchangeReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CoinsExchangeReq) GetGenre() int64 {
	if x != nil {
		return x.Genre
	}
	return 0
}

func (x *CoinsExchangeReq) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type CoinsExchangeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // 交易ID
	Code int64  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`            // 状态码
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`             // 描述信息
}

func (x *CoinsExchangeResp) Reset() {
	*x = CoinsExchangeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinsExchangeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinsExchangeResp) ProtoMessage() {}

func (x *CoinsExchangeResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinsExchangeResp.ProtoReflect.Descriptor instead.
func (*CoinsExchangeResp) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{6}
}

func (x *CoinsExchangeResp) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *CoinsExchangeResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CoinsExchangeResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type CheckBalanceCoinsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                     // 账户
	OrgMspId string `protobuf:"bytes,2,opt,name=org_msp_id,json=orgMspId,proto3" json:"org_msp_id,omitempty"` // 账户所属组织
}

func (x *CheckBalanceCoinsReq) Reset() {
	*x = CheckBalanceCoinsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckBalanceCoinsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBalanceCoinsReq) ProtoMessage() {}

func (x *CheckBalanceCoinsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBalanceCoinsReq.ProtoReflect.Descriptor instead.
func (*CheckBalanceCoinsReq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{7}
}

func (x *CheckBalanceCoinsReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CheckBalanceCoinsReq) GetOrgMspId() string {
	if x != nil {
		return x.OrgMspId
	}
	return ""
}

type CheckBalanceCoinsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Desc    string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`       // 描述信息
	Balance string `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"` // 余额(单位:分)
}

func (x *CheckBalanceCoinsResp) Reset() {
	*x = CheckBalanceCoinsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_assets_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckBalanceCoinsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBalanceCoinsResp) ProtoMessage() {}

func (x *CheckBalanceCoinsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_assets_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBalanceCoinsResp.ProtoReflect.Descriptor instead.
func (*CheckBalanceCoinsResp) Descriptor() ([]byte, []int) {
	return file_pkg_pb_assets_proto_rawDescGZIP(), []int{8}
}

func (x *CheckBalanceCoinsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckBalanceCoinsResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CheckBalanceCoinsResp) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

var File_pkg_pb_assets_proto protoreflect.FileDescriptor

var file_pkg_pb_assets_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0d, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5e, 0x0a, 0x0c, 0x4d, 0x69, 0x6e,
	0x74, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x0a, 0x6f, 0x72, 0x67, 0x5f, 0x6d, 0x73, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x67, 0x4d, 0x73, 0x70, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4f, 0x0a, 0x0d, 0x4d, 0x69, 0x6e,
	0x74, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f,
	0x72, 0x67, 0x22, 0x53, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x97, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x69, 0x6e,
	0x73, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x0a, 0x6f, 0x72, 0x67, 0x5f, 0x6d, 0x73,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x67, 0x4d,
	0x73, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x50, 0x0a, 0x11, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x22, 0x4e, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x0a, 0x6f, 0x72, 0x67, 0x5f, 0x6d, 0x73, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x67, 0x4d, 0x73,
	0x70, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x32, 0x3d,
	0x0a, 0x06, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_assets_proto_rawDescOnce sync.Once
	file_pkg_pb_assets_proto_rawDescData = file_pkg_pb_assets_proto_rawDesc
)

func file_pkg_pb_assets_proto_rawDescGZIP() []byte {
	file_pkg_pb_assets_proto_rawDescOnce.Do(func() {
		file_pkg_pb_assets_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_assets_proto_rawDescData)
	})
	return file_pkg_pb_assets_proto_rawDescData
}

var file_pkg_pb_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_pb_assets_proto_goTypes = []interface{}{
	(*UniversalResp)(nil),         // 0: UniversalResp
	(*MintCoinsReq)(nil),          // 1: MintCoinsReq
	(*MintCoinsResp)(nil),         // 2: MintCoinsResp
	(*UserData)(nil),              // 3: UserData
	(*RegisterResp)(nil),          // 4: RegisterResp
	(*CoinsExchangeReq)(nil),      // 5: CoinsExchangeReq
	(*CoinsExchangeResp)(nil),     // 6: CoinsExchangeResp
	(*CheckBalanceCoinsReq)(nil),  // 7: CheckBalanceCoinsReq
	(*CheckBalanceCoinsResp)(nil), // 8: CheckBalanceCoinsResp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_pkg_pb_assets_proto_depIdxs = []int32{
	3, // 0: RegisterResp.data:type_name -> UserData
	9, // 1: Wallet.Register:input_type -> google.protobuf.Empty
	4, // 2: Wallet.Register:output_type -> RegisterResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_pb_assets_proto_init() }
func file_pkg_pb_assets_proto_init() {
	if File_pkg_pb_assets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_assets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_assets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MintCoinsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_assets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MintCoinsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_assets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_assets_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_assets_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinsExchangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_assets_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinsExchangeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_assets_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckBalanceCoinsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_assets_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckBalanceCoinsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_assets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_assets_proto_goTypes,
		DependencyIndexes: file_pkg_pb_assets_proto_depIdxs,
		MessageInfos:      file_pkg_pb_assets_proto_msgTypes,
	}.Build()
	File_pkg_pb_assets_proto = out.File
	file_pkg_pb_assets_proto_rawDesc = nil
	file_pkg_pb_assets_proto_goTypes = nil
	file_pkg_pb_assets_proto_depIdxs = nil
}
