// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/pb/assets.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UniversalResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UniversalResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UniversalResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UniversalRespMultiError, or
// nil if none found.
func (m *UniversalResp) ValidateAll() error {
	return m.validate(true)
}

func (m *UniversalResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if len(errors) > 0 {
		return UniversalRespMultiError(errors)
	}

	return nil
}

// UniversalRespMultiError is an error wrapping multiple validation errors
// returned by UniversalResp.ValidateAll() if the designated constraints
// aren't met.
type UniversalRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UniversalRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UniversalRespMultiError) AllErrors() []error { return m }

// UniversalRespValidationError is the validation error returned by
// UniversalResp.Validate if the designated constraints aren't met.
type UniversalRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UniversalRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UniversalRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UniversalRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UniversalRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UniversalRespValidationError) ErrorName() string { return "UniversalRespValidationError" }

// Error satisfies the builtin error interface
func (e UniversalRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUniversalResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UniversalRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UniversalRespValidationError{}

// Validate checks the field values on MintCoinsReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MintCoinsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MintCoinsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MintCoinsReqMultiError, or
// nil if none found.
func (m *MintCoinsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *MintCoinsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	// no validation rules for OrgMspId

	// no validation rules for Amount

	if len(errors) > 0 {
		return MintCoinsReqMultiError(errors)
	}

	return nil
}

// MintCoinsReqMultiError is an error wrapping multiple validation errors
// returned by MintCoinsReq.ValidateAll() if the designated constraints aren't met.
type MintCoinsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MintCoinsReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MintCoinsReqMultiError) AllErrors() []error { return m }

// MintCoinsReqValidationError is the validation error returned by
// MintCoinsReq.Validate if the designated constraints aren't met.
type MintCoinsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MintCoinsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MintCoinsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MintCoinsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MintCoinsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MintCoinsReqValidationError) ErrorName() string { return "MintCoinsReqValidationError" }

// Error satisfies the builtin error interface
func (e MintCoinsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMintCoinsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MintCoinsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MintCoinsReqValidationError{}

// Validate checks the field values on MintCoinsResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MintCoinsResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MintCoinsResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MintCoinsRespMultiError, or
// nil if none found.
func (m *MintCoinsResp) ValidateAll() error {
	return m.validate(true)
}

func (m *MintCoinsResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Desc

	// no validation rules for Amount

	if len(errors) > 0 {
		return MintCoinsRespMultiError(errors)
	}

	return nil
}

// MintCoinsRespMultiError is an error wrapping multiple validation errors
// returned by MintCoinsResp.ValidateAll() if the designated constraints
// aren't met.
type MintCoinsRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MintCoinsRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MintCoinsRespMultiError) AllErrors() []error { return m }

// MintCoinsRespValidationError is the validation error returned by
// MintCoinsResp.Validate if the designated constraints aren't met.
type MintCoinsRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MintCoinsRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MintCoinsRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MintCoinsRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MintCoinsRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MintCoinsRespValidationError) ErrorName() string { return "MintCoinsRespValidationError" }

// Error satisfies the builtin error interface
func (e MintCoinsRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMintCoinsResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MintCoinsRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MintCoinsRespValidationError{}

// Validate checks the field values on UserData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserDataMultiError, or nil
// if none found.
func (m *UserData) ValidateAll() error {
	return m.validate(true)
}

func (m *UserData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Account

	// no validation rules for Org

	if len(errors) > 0 {
		return UserDataMultiError(errors)
	}

	return nil
}

// UserDataMultiError is an error wrapping multiple validation errors returned
// by UserData.ValidateAll() if the designated constraints aren't met.
type UserDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserDataMultiError) AllErrors() []error { return m }

// UserDataValidationError is the validation error returned by
// UserData.Validate if the designated constraints aren't met.
type UserDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDataValidationError) ErrorName() string { return "UserDataValidationError" }

// Error satisfies the builtin error interface
func (e UserDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDataValidationError{}

// Validate checks the field values on RegisterResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RegisterResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RegisterRespMultiError, or
// nil if none found.
func (m *RegisterResp) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RegisterRespMultiError(errors)
	}

	return nil
}

// RegisterRespMultiError is an error wrapping multiple validation errors
// returned by RegisterResp.ValidateAll() if the designated constraints aren't met.
type RegisterRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterRespMultiError) AllErrors() []error { return m }

// RegisterRespValidationError is the validation error returned by
// RegisterResp.Validate if the designated constraints aren't met.
type RegisterRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterRespValidationError) ErrorName() string { return "RegisterRespValidationError" }

// Error satisfies the builtin error interface
func (e RegisterRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterRespValidationError{}

// Validate checks the field values on CoinsExchangeReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CoinsExchangeReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CoinsExchangeReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CoinsExchangeReqMultiError, or nil if none found.
func (m *CoinsExchangeReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CoinsExchangeReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	// no validation rules for OrgMspId

	// no validation rules for Amount

	// no validation rules for Genre

	// no validation rules for PaymentId

	if len(errors) > 0 {
		return CoinsExchangeReqMultiError(errors)
	}

	return nil
}

// CoinsExchangeReqMultiError is an error wrapping multiple validation errors
// returned by CoinsExchangeReq.ValidateAll() if the designated constraints
// aren't met.
type CoinsExchangeReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CoinsExchangeReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CoinsExchangeReqMultiError) AllErrors() []error { return m }

// CoinsExchangeReqValidationError is the validation error returned by
// CoinsExchangeReq.Validate if the designated constraints aren't met.
type CoinsExchangeReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CoinsExchangeReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CoinsExchangeReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CoinsExchangeReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CoinsExchangeReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CoinsExchangeReqValidationError) ErrorName() string { return "CoinsExchangeReqValidationError" }

// Error satisfies the builtin error interface
func (e CoinsExchangeReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCoinsExchangeReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CoinsExchangeReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CoinsExchangeReqValidationError{}

// Validate checks the field values on CoinsExchangeResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CoinsExchangeResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CoinsExchangeResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CoinsExchangeRespMultiError, or nil if none found.
func (m *CoinsExchangeResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CoinsExchangeResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxId

	// no validation rules for Code

	// no validation rules for Desc

	if len(errors) > 0 {
		return CoinsExchangeRespMultiError(errors)
	}

	return nil
}

// CoinsExchangeRespMultiError is an error wrapping multiple validation errors
// returned by CoinsExchangeResp.ValidateAll() if the designated constraints
// aren't met.
type CoinsExchangeRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CoinsExchangeRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CoinsExchangeRespMultiError) AllErrors() []error { return m }

// CoinsExchangeRespValidationError is the validation error returned by
// CoinsExchangeResp.Validate if the designated constraints aren't met.
type CoinsExchangeRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CoinsExchangeRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CoinsExchangeRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CoinsExchangeRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CoinsExchangeRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CoinsExchangeRespValidationError) ErrorName() string {
	return "CoinsExchangeRespValidationError"
}

// Error satisfies the builtin error interface
func (e CoinsExchangeRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCoinsExchangeResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CoinsExchangeRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CoinsExchangeRespValidationError{}

// Validate checks the field values on CheckBalanceCoinsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckBalanceCoinsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckBalanceCoinsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckBalanceCoinsReqMultiError, or nil if none found.
func (m *CheckBalanceCoinsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckBalanceCoinsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	// no validation rules for OrgMspId

	if len(errors) > 0 {
		return CheckBalanceCoinsReqMultiError(errors)
	}

	return nil
}

// CheckBalanceCoinsReqMultiError is an error wrapping multiple validation
// errors returned by CheckBalanceCoinsReq.ValidateAll() if the designated
// constraints aren't met.
type CheckBalanceCoinsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckBalanceCoinsReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckBalanceCoinsReqMultiError) AllErrors() []error { return m }

// CheckBalanceCoinsReqValidationError is the validation error returned by
// CheckBalanceCoinsReq.Validate if the designated constraints aren't met.
type CheckBalanceCoinsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckBalanceCoinsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckBalanceCoinsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckBalanceCoinsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckBalanceCoinsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckBalanceCoinsReqValidationError) ErrorName() string {
	return "CheckBalanceCoinsReqValidationError"
}

// Error satisfies the builtin error interface
func (e CheckBalanceCoinsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckBalanceCoinsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckBalanceCoinsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckBalanceCoinsReqValidationError{}

// Validate checks the field values on CheckBalanceCoinsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckBalanceCoinsResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckBalanceCoinsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckBalanceCoinsRespMultiError, or nil if none found.
func (m *CheckBalanceCoinsResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckBalanceCoinsResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Desc

	// no validation rules for Balance

	if len(errors) > 0 {
		return CheckBalanceCoinsRespMultiError(errors)
	}

	return nil
}

// CheckBalanceCoinsRespMultiError is an error wrapping multiple validation
// errors returned by CheckBalanceCoinsResp.ValidateAll() if the designated
// constraints aren't met.
type CheckBalanceCoinsRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckBalanceCoinsRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckBalanceCoinsRespMultiError) AllErrors() []error { return m }

// CheckBalanceCoinsRespValidationError is the validation error returned by
// CheckBalanceCoinsResp.Validate if the designated constraints aren't met.
type CheckBalanceCoinsRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckBalanceCoinsRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckBalanceCoinsRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckBalanceCoinsRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckBalanceCoinsRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckBalanceCoinsRespValidationError) ErrorName() string {
	return "CheckBalanceCoinsRespValidationError"
}

// Error satisfies the builtin error interface
func (e CheckBalanceCoinsRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckBalanceCoinsResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckBalanceCoinsRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckBalanceCoinsRespValidationError{}
