// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: pkg/pb/tickets_v2.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BlockChainTicketServer_MainOrderTicket_FullMethodName = "/BlockChainTicketServer/mainOrderTicket"
)

// BlockChainTicketServerClient is the client API for BlockChainTicketServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockChainTicketServerClient interface {
	MainOrderTicket(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type blockChainTicketServerClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockChainTicketServerClient(cc grpc.ClientConnInterface) BlockChainTicketServerClient {
	return &blockChainTicketServerClient{cc}
}

func (c *blockChainTicketServerClient) MainOrderTicket(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, BlockChainTicketServer_MainOrderTicket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockChainTicketServerServer is the server API for BlockChainTicketServer service.
// All implementations must embed UnimplementedBlockChainTicketServerServer
// for forward compatibility
type BlockChainTicketServerServer interface {
	MainOrderTicket(context.Context, *RequestMessage) (*ResponseMessage, error)
//	mustEmbedUnimplementedBlockChainTicketServerServer()
}

// UnimplementedBlockChainTicketServerServer must be embedded to have forward compatible implementations.
type UnimplementedBlockChainTicketServerServer struct {
}

func (UnimplementedBlockChainTicketServerServer) MainOrderTicket(context.Context, *RequestMessage) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MainOrderTicket not implemented")
}
func (UnimplementedBlockChainTicketServerServer) mustEmbedUnimplementedBlockChainTicketServerServer() {
}

// UnsafeBlockChainTicketServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockChainTicketServerServer will
// result in compilation errors.
type UnsafeBlockChainTicketServerServer interface {
	mustEmbedUnimplementedBlockChainTicketServerServer()
}

func RegisterBlockChainTicketServerServer(s grpc.ServiceRegistrar, srv BlockChainTicketServerServer) {
	s.RegisterService(&BlockChainTicketServer_ServiceDesc, srv)
}

func _BlockChainTicketServer_MainOrderTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainTicketServerServer).MainOrderTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockChainTicketServer_MainOrderTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainTicketServerServer).MainOrderTicket(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockChainTicketServer_ServiceDesc is the grpc.ServiceDesc for BlockChainTicketServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockChainTicketServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BlockChainTicketServer",
	HandlerType: (*BlockChainTicketServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "mainOrderTicket",
			Handler:    _BlockChainTicketServer_MainOrderTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/tickets_v2.proto",
}
