// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/pb/trade.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpsertCreditAmountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertCreditAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertCreditAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertCreditAmountRequestMultiError, or nil if none found.
func (m *UpsertCreditAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertCreditAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetUpsertCreditData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertCreditAmountRequestValidationError{
					field:  "UpsertCreditData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertCreditAmountRequestValidationError{
					field:  "UpsertCreditData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpsertCreditData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertCreditAmountRequestValidationError{
				field:  "UpsertCreditData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpsertCreditAmountRequestMultiError(errors)
	}

	return nil
}

// UpsertCreditAmountRequestMultiError is an error wrapping multiple validation
// errors returned by UpsertCreditAmountRequest.ValidateAll() if the
// designated constraints aren't met.
type UpsertCreditAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertCreditAmountRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertCreditAmountRequestMultiError) AllErrors() []error { return m }

// UpsertCreditAmountRequestValidationError is the validation error returned by
// UpsertCreditAmountRequest.Validate if the designated constraints aren't met.
type UpsertCreditAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertCreditAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertCreditAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertCreditAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertCreditAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertCreditAmountRequestValidationError) ErrorName() string {
	return "UpsertCreditAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertCreditAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertCreditAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertCreditAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertCreditAmountRequestValidationError{}

// Validate checks the field values on UpsertCreditData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpsertCreditData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertCreditData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertCreditDataMultiError, or nil if none found.
func (m *UpsertCreditData) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertCreditData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetMerchantId()) < 0 {
		err := UpsertCreditDataValidationError{
			field:  "MerchantId",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for MerchantName

	// no validation rules for Amount

	// no validation rules for PledgeAmount

	if utf8.RuneCountInString(m.GetAccount()) != 42 {
		err := UpsertCreditDataValidationError{
			field:  "Account",
			reason: "value length must be 42 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if utf8.RuneCountInString(m.GetOrg()) < 0 {
		err := UpsertCreditDataValidationError{
			field:  "Org",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAssetsKey()) < 0 {
		err := UpsertCreditDataValidationError{
			field:  "AssetsKey",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSeqNo()) < 0 {
		err := UpsertCreditDataValidationError{
			field:  "SeqNo",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpsertCreditDataMultiError(errors)
	}

	return nil
}

// UpsertCreditDataMultiError is an error wrapping multiple validation errors
// returned by UpsertCreditData.ValidateAll() if the designated constraints
// aren't met.
type UpsertCreditDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertCreditDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertCreditDataMultiError) AllErrors() []error { return m }

// UpsertCreditDataValidationError is the validation error returned by
// UpsertCreditData.Validate if the designated constraints aren't met.
type UpsertCreditDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertCreditDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertCreditDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertCreditDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertCreditDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertCreditDataValidationError) ErrorName() string { return "UpsertCreditDataValidationError" }

// Error satisfies the builtin error interface
func (e UpsertCreditDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertCreditData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertCreditDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertCreditDataValidationError{}

// Validate checks the field values on UpsertCreditAmountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertCreditAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertCreditAmountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertCreditAmountResponseMultiError, or nil if none found.
func (m *UpsertCreditAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertCreditAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertCreditAmountResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertCreditAmountResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertCreditAmountResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpsertCreditAmountResponseMultiError(errors)
	}

	return nil
}

// UpsertCreditAmountResponseMultiError is an error wrapping multiple
// validation errors returned by UpsertCreditAmountResponse.ValidateAll() if
// the designated constraints aren't met.
type UpsertCreditAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertCreditAmountResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertCreditAmountResponseMultiError) AllErrors() []error { return m }

// UpsertCreditAmountResponseValidationError is the validation error returned
// by UpsertCreditAmountResponse.Validate if the designated constraints aren't met.
type UpsertCreditAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertCreditAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertCreditAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertCreditAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertCreditAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertCreditAmountResponseValidationError) ErrorName() string {
	return "UpsertCreditAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertCreditAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertCreditAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertCreditAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertCreditAmountResponseValidationError{}

// Validate checks the field values on TradeTxData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TradeTxData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TradeTxData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TradeTxDataMultiError, or
// nil if none found.
func (m *TradeTxData) ValidateAll() error {
	return m.validate(true)
}

func (m *TradeTxData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TxId

	if len(errors) > 0 {
		return TradeTxDataMultiError(errors)
	}

	return nil
}

// TradeTxDataMultiError is an error wrapping multiple validation errors
// returned by TradeTxData.ValidateAll() if the designated constraints aren't met.
type TradeTxDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TradeTxDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TradeTxDataMultiError) AllErrors() []error { return m }

// TradeTxDataValidationError is the validation error returned by
// TradeTxData.Validate if the designated constraints aren't met.
type TradeTxDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TradeTxDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TradeTxDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TradeTxDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TradeTxDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TradeTxDataValidationError) ErrorName() string { return "TradeTxDataValidationError" }

// Error satisfies the builtin error interface
func (e TradeTxDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTradeTxData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TradeTxDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TradeTxDataValidationError{}

// Validate checks the field values on TransferCreditRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TransferCreditRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransferCreditRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransferCreditRequestMultiError, or nil if none found.
func (m *TransferCreditRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TransferCreditRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetIssuerId()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "IssuerId",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetIssuerName()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "IssuerName",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetIssuerAccount()) != 42 {
		err := TransferCreditRequestValidationError{
			field:  "IssuerAccount",
			reason: "value length must be 42 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if utf8.RuneCountInString(m.GetIssuerOrg()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "IssuerOrg",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetReceiverId()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "ReceiverId",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetReceiverName()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "ReceiverName",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetReceiverAccount()) != 42 {
		err := TransferCreditRequestValidationError{
			field:  "ReceiverAccount",
			reason: "value length must be 42 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if utf8.RuneCountInString(m.GetReceiverOrg()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "ReceiverOrg",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAmount()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "Amount",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTradeNo()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "TradeNo",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOutTradeNo()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "OutTradeNo",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetGoodsName()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "GoodsName",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAssetsKey()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "AssetsKey",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPaymentTime()) < 0 {
		err := TransferCreditRequestValidationError{
			field:  "PaymentTime",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TransferCreditRequestMultiError(errors)
	}

	return nil
}

// TransferCreditRequestMultiError is an error wrapping multiple validation
// errors returned by TransferCreditRequest.ValidateAll() if the designated
// constraints aren't met.
type TransferCreditRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransferCreditRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransferCreditRequestMultiError) AllErrors() []error { return m }

// TransferCreditRequestValidationError is the validation error returned by
// TransferCreditRequest.Validate if the designated constraints aren't met.
type TransferCreditRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransferCreditRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransferCreditRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransferCreditRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransferCreditRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransferCreditRequestValidationError) ErrorName() string {
	return "TransferCreditRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TransferCreditRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransferCreditRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransferCreditRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransferCreditRequestValidationError{}

// Validate checks the field values on TransferCreditResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TransferCreditResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransferCreditResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransferCreditResponseMultiError, or nil if none found.
func (m *TransferCreditResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TransferCreditResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransferCreditResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransferCreditResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransferCreditResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TransferCreditResponseMultiError(errors)
	}

	return nil
}

// TransferCreditResponseMultiError is an error wrapping multiple validation
// errors returned by TransferCreditResponse.ValidateAll() if the designated
// constraints aren't met.
type TransferCreditResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransferCreditResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransferCreditResponseMultiError) AllErrors() []error { return m }

// TransferCreditResponseValidationError is the validation error returned by
// TransferCreditResponse.Validate if the designated constraints aren't met.
type TransferCreditResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransferCreditResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransferCreditResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransferCreditResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransferCreditResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransferCreditResponseValidationError) ErrorName() string {
	return "TransferCreditResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TransferCreditResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransferCreditResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransferCreditResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransferCreditResponseValidationError{}

// Validate checks the field values on PaymentFlowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PaymentFlowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentFlowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PaymentFlowRequestMultiError, or nil if none found.
func (m *PaymentFlowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentFlowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTradeNo()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "TradeNo",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAmount()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "Amount",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTransactionSerialNumber()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "TransactionSerialNumber",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCreditorId()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "CreditorId",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCreditorName()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "CreditorName",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDebtorId()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "DebtorId",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDebtorName()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "DebtorName",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPaymentTime()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "PaymentTime",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBankCardNumber()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "BankCardNumber",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBankName()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "BankName",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCorporationId()) < 0 {
		err := PaymentFlowRequestValidationError{
			field:  "CorporationId",
			reason: "value length must be at least 0 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PaymentFlowRequestMultiError(errors)
	}

	return nil
}

// PaymentFlowRequestMultiError is an error wrapping multiple validation errors
// returned by PaymentFlowRequest.ValidateAll() if the designated constraints
// aren't met.
type PaymentFlowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentFlowRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentFlowRequestMultiError) AllErrors() []error { return m }

// PaymentFlowRequestValidationError is the validation error returned by
// PaymentFlowRequest.Validate if the designated constraints aren't met.
type PaymentFlowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentFlowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentFlowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentFlowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentFlowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentFlowRequestValidationError) ErrorName() string {
	return "PaymentFlowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PaymentFlowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentFlowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentFlowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentFlowRequestValidationError{}

// Validate checks the field values on PaymentFlowResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PaymentFlowResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentFlowResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PaymentFlowResponseMultiError, or nil if none found.
func (m *PaymentFlowResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentFlowResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Msg

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PaymentFlowResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PaymentFlowResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PaymentFlowResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PaymentFlowResponseMultiError(errors)
	}

	return nil
}

// PaymentFlowResponseMultiError is an error wrapping multiple validation
// errors returned by PaymentFlowResponse.ValidateAll() if the designated
// constraints aren't met.
type PaymentFlowResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentFlowResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentFlowResponseMultiError) AllErrors() []error { return m }

// PaymentFlowResponseValidationError is the validation error returned by
// PaymentFlowResponse.Validate if the designated constraints aren't met.
type PaymentFlowResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentFlowResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentFlowResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentFlowResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentFlowResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentFlowResponseValidationError) ErrorName() string {
	return "PaymentFlowResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PaymentFlowResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentFlowResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentFlowResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentFlowResponseValidationError{}
