// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: pkg/pb/trade.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TradeBlockChain_UpsertCreditAmount_FullMethodName = "/TradeBlockChain/UpsertCreditAmount"
	TradeBlockChain_TransferCredit_FullMethodName     = "/TradeBlockChain/TransferCredit"
	TradeBlockChain_ProcessPaymentFlow_FullMethodName = "/TradeBlockChain/ProcessPaymentFlow"
)

// TradeBlockChainClient is the client API for TradeBlockChain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeBlockChainClient interface {
	UpsertCreditAmount(ctx context.Context, in *UpsertCreditAmountRequest, opts ...grpc.CallOption) (*UpsertCreditAmountResponse, error)
	TransferCredit(ctx context.Context, in *TransferCreditRequest, opts ...grpc.CallOption) (*TransferCreditResponse, error)
	ProcessPaymentFlow(ctx context.Context, in *PaymentFlowRequest, opts ...grpc.CallOption) (*PaymentFlowResponse, error)
}

type tradeBlockChainClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeBlockChainClient(cc grpc.ClientConnInterface) TradeBlockChainClient {
	return &tradeBlockChainClient{cc}
}

func (c *tradeBlockChainClient) UpsertCreditAmount(ctx context.Context, in *UpsertCreditAmountRequest, opts ...grpc.CallOption) (*UpsertCreditAmountResponse, error) {
	out := new(UpsertCreditAmountResponse)
	err := c.cc.Invoke(ctx, TradeBlockChain_UpsertCreditAmount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeBlockChainClient) TransferCredit(ctx context.Context, in *TransferCreditRequest, opts ...grpc.CallOption) (*TransferCreditResponse, error) {
	out := new(TransferCreditResponse)
	err := c.cc.Invoke(ctx, TradeBlockChain_TransferCredit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeBlockChainClient) ProcessPaymentFlow(ctx context.Context, in *PaymentFlowRequest, opts ...grpc.CallOption) (*PaymentFlowResponse, error) {
	out := new(PaymentFlowResponse)
	err := c.cc.Invoke(ctx, TradeBlockChain_ProcessPaymentFlow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeBlockChainServer is the server API for TradeBlockChain service.
// All implementations must embed UnimplementedTradeBlockChainServer
// for forward compatibility
type TradeBlockChainServer interface {
	UpsertCreditAmount(context.Context, *UpsertCreditAmountRequest) (*UpsertCreditAmountResponse, error)
	TransferCredit(context.Context, *TransferCreditRequest) (*TransferCreditResponse, error)
	ProcessPaymentFlow(context.Context, *PaymentFlowRequest) (*PaymentFlowResponse, error)
}

// UnimplementedTradeBlockChainServer must be embedded to have forward compatible implementations.
type UnimplementedTradeBlockChainServer struct {
}

func (UnimplementedTradeBlockChainServer) UpsertCreditAmount(context.Context, *UpsertCreditAmountRequest) (*UpsertCreditAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertCreditAmount not implemented")
}
func (UnimplementedTradeBlockChainServer) TransferCredit(context.Context, *TransferCreditRequest) (*TransferCreditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferCredit not implemented")
}
func (UnimplementedTradeBlockChainServer) ProcessPaymentFlow(context.Context, *PaymentFlowRequest) (*PaymentFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPaymentFlow not implemented")
}
func (UnimplementedTradeBlockChainServer) mustEmbedUnimplementedTradeBlockChainServer() {}

// UnsafeTradeBlockChainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeBlockChainServer will
// result in compilation errors.
type UnsafeTradeBlockChainServer interface {
	mustEmbedUnimplementedTradeBlockChainServer()
}

func RegisterTradeBlockChainServer(s grpc.ServiceRegistrar, srv TradeBlockChainServer) {
	s.RegisterService(&TradeBlockChain_ServiceDesc, srv)
}

func _TradeBlockChain_UpsertCreditAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCreditAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeBlockChainServer).UpsertCreditAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeBlockChain_UpsertCreditAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeBlockChainServer).UpsertCreditAmount(ctx, req.(*UpsertCreditAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeBlockChain_TransferCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferCreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeBlockChainServer).TransferCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeBlockChain_TransferCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeBlockChainServer).TransferCredit(ctx, req.(*TransferCreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeBlockChain_ProcessPaymentFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeBlockChainServer).ProcessPaymentFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeBlockChain_ProcessPaymentFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeBlockChainServer).ProcessPaymentFlow(ctx, req.(*PaymentFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeBlockChain_ServiceDesc is the grpc.ServiceDesc for TradeBlockChain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeBlockChain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TradeBlockChain",
	HandlerType: (*TradeBlockChainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertCreditAmount",
			Handler:    _TradeBlockChain_UpsertCreditAmount_Handler,
		},
		{
			MethodName: "TransferCredit",
			Handler:    _TradeBlockChain_TransferCredit_Handler,
		},
		{
			MethodName: "ProcessPaymentFlow",
			Handler:    _TradeBlockChain_ProcessPaymentFlow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/trade.proto",
}
